// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8XuRECxv8VA897Ixm5ruKO4NhqtD6Hc',
    appId: '1:12778824576:web:82ab80a2ed8d2fd6555765',
    messagingSenderId: '12778824576',
    projectId: 'spotify-dc00a',
    authDomain: 'spotify-dc00a.firebaseapp.com',
    storageBucket: 'spotify-dc00a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBveq4OXz9FHjZEhA6afTdj4qtMmJS3sIU',
    appId: '1:12778824576:android:09a97da1b82ce8f5555765',
    messagingSenderId: '12778824576',
    projectId: 'spotify-dc00a',
    storageBucket: 'spotify-dc00a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI2IA5hmgtedunaZg-raqWWKPW41RScyo',
    appId: '1:12778824576:ios:22555f2d2267996c555765',
    messagingSenderId: '12778824576',
    projectId: 'spotify-dc00a',
    storageBucket: 'spotify-dc00a.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI2IA5hmgtedunaZg-raqWWKPW41RScyo',
    appId: '1:12778824576:ios:22555f2d2267996c555765',
    messagingSenderId: '12778824576',
    projectId: 'spotify-dc00a',
    storageBucket: 'spotify-dc00a.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk8XuRECxv8VA897Ixm5ruKO4NhqtD6Hc',
    appId: '1:12778824576:web:6aba2001df7be7fa555765',
    messagingSenderId: '12778824576',
    projectId: 'spotify-dc00a',
    authDomain: 'spotify-dc00a.firebaseapp.com',
    storageBucket: 'spotify-dc00a.appspot.com',
  );

}